//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRI.Maptor.Res.LRSimplification.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRI.Maptor.Res.LRSimplification.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic Regression.
        /// </summary>
        internal static string lr_expanderTitle_logisticRegression {
            get {
                return ResourceManager.GetString("lr_expanderTitle_logisticRegression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string lr_expanderTitle_settings {
            get {
                return ResourceManager.GetString("lr_expanderTitle_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string lr_expanderTitle_tools {
            get {
                return ResourceManager.GetString("lr_expanderTitle_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthetic Training Data.
        /// </summary>
        internal static string lr_expanderTitle_trainingData {
            get {
                return ResourceManager.GetString("lr_expanderTitle_trainingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear LR model.
        /// </summary>
        internal static string lr_model_clearModel {
            get {
                return ResourceManager.GetString("lr_model_clearModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load LR model ....
        /// </summary>
        internal static string lr_model_loadModel {
            get {
                return ResourceManager.GetString("lr_model_loadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save LR model (csv) ....
        /// </summary>
        internal static string lr_model_saveModelAsCsv {
            get {
                return ResourceManager.GetString("lr_model_saveModelAsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save LR model (json) ....
        /// </summary>
        internal static string lr_model_saveModelAsJson {
            get {
                return ResourceManager.GetString("lr_model_saveModelAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string lr_training_cmd_add {
            get {
                return ResourceManager.GetString("lr_training_cmd_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build LR Model.
        /// </summary>
        internal static string lr_training_cmd_buildLRModel {
            get {
                return ResourceManager.GetString("lr_training_cmd_buildLRModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string lr_training_cmd_clearAll {
            get {
                return ResourceManager.GetString("lr_training_cmd_clearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string lr_training_cmd_load {
            get {
                return ResourceManager.GetString("lr_training_cmd_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string lr_training_cmd_new {
            get {
                return ResourceManager.GetString("lr_training_cmd_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string lr_training_cmd_save {
            get {
                return ResourceManager.GetString("lr_training_cmd_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string lr_training_cmd_selectAll {
            get {
                return ResourceManager.GetString("lr_training_cmd_selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string lr_training_listHeader {
            get {
                return ResourceManager.GetString("lr_training_listHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Features.
        /// </summary>
        internal static string lr_training_modelFeatures {
            get {
                return ResourceManager.GetString("lr_training_modelFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lr_training_name {
            get {
                return ResourceManager.GetString("lr_training_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string lr_training_original {
            get {
                return ResourceManager.GetString("lr_training_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string lr_training_parameters {
            get {
                return ResourceManager.GetString("lr_training_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retain intermediate points.
        /// </summary>
        internal static string lr_training_retainIntermediatePoint {
            get {
                return ResourceManager.GetString("lr_training_retainIntermediatePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified.
        /// </summary>
        internal static string lr_training_simplified {
            get {
                return ResourceManager.GetString("lr_training_simplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Simplification using Logistic Regression (Demo App).
        /// </summary>
        internal static string lr_ui_title {
            get {
                return ResourceManager.GetString("lr_ui_title", resourceCulture);
            }
        }
    }
}
