//namespace IRI.Maptor.Jab.Common.Localization;

//public enum LocalizationResourceKeys
//{
//    cmd_drawingLegend_addGeoJson,
//    cmd_drawingLegend_addLatLongTxt,
//    cmd_drawingLegend_addShapefile,
//    cmd_drawingLegend_moveDown,
//    cmd_drawingLegend_moveUp,
//    cmd_drawingLegend_removeAll,

//    cmd_general_addShapefile,
//    cmd_general_addTextToMap,
//    cmd_general_clearAll,
//    cmd_general_drawPoint,
//    cmd_general_drawPolygon,
//    cmd_general_drawPolyline,
//    cmd_general_fullExtent,
//    cmd_general_goTo,
//    cmd_general_measureArea,
//    cmd_general_measureLength,

//    cmd_general_pan,
//    cmd_general_zoomIn,
//    cmd_general_zoomOut,
//    cmd_general_zoomPrevious,
//    cmd_general_zoomNext,

//    cmd_drawingLegendItem_boundary,
//    cmd_drawingLegendItem_breakIntoGeometries,
//    cmd_drawingLegendItem_breakIntoPoints,
//    cmd_legendItem_clearSelected,
//    cmd_drawingLegendItem_convexHull,
//    cmd_drawingLegendItem_downloadRegionImages,
//    cmd_drawingLegendItem_duplicateFeature,
//    cmd_drawingLegendItem_edit,
//    cmd_drawingLegendItem_envelope,
//    cmd_drawingLegendItem_exportAsGeoJson,
//    cmd_drawingLegendItem_exportAsPng,
//    cmd_drawingLegendItem_exportAsShapefile,
//    cmd_drawingLegendItem_exteriorRing,
//    cmd_drawingLegendItem_remove,
//    cmd_legendItem_selectByDrawing,
//    cmd_legendItem_showAttributes,
//    cmd_legendItem_showSymbology,
//    cmd_legendItem_toggleLayerLabel,
//    cmd_legendItem_zoomToExtent,
//    cmd_legendItem_exportAsPng,
//    cmd_legendItem_exportAsShapefile,
//    cmd_legendItem_exportAsGeoJson,
//    cmd_legendItem_remove,

//    map_draw_addPoint,
//    map_draw_cancelDrawing,
//    map_draw_finishDrawingPart,
//    map_draw_finishDrawing,
//    map_draw_newDrawing,

//    dialog_goto_title,
//    dialog_goto_panTo,
//    dialog_goto_zoomTo,

//    dialog_symbology_title,
//    dialog_symbology_fill,
//    dialog_symbology_stroke,
//    dialog_symbology_strokeWidth,
     
//    mapPanel_currentPoint_title,
//    mapPanel_currentPart_title,
//    mapPanel_srs_title,

//    srs_ceaSubTitle,
//    srs_ceaTitle,
//    srs_defaultLatitude,
//    srs_defaultLongitude,
//    srs_defaultX,
//    srs_defaultY,
//    srs_geodeticDmsSubTitle,
//    srs_geodeticDmsTitle,
//    srs_geodeticSubTitle,
//    srs_geodeticTitle,
//    srs_mercatorSubTitle,
//    srs_mercatorTitle,
//    srs_tmSubTitle,
//    srs_tmTitle,
//    srs_utmSubTitle,
//    srs_utmTitle,
//    srs_utmZone,
//    srs_webMercatorTitle,
//    srs_webMercatorSubTitle,

//    tile_provider_bing,
//    tile_provider_carto,
//    tile_provider_google,
//    tile_provider_mapbox,
//    tile_provider_nokia,
//    tile_provider_osm,
//    tile_provider_waze,
//    tile_provider_yandex,
//    tile_mapType_CleanGrey,
//    tile_mapType_BlackWhite,
//    tile_mapType_Traffic,
//    tile_mapType_Satellite,
//    tile_mapType_Hybrid,
//    tile_mapType_RoadMap,
//    tile_mapType_Terrain,
//    tile_mapType_Light,
//    tile_mapType_Nature,
//    tile_mapType_NeutralBlue,
//    tile_mapType_Street,
//    tile_mapType_Topo,
//    tile_mapType_MapyWinter,
//    tile_mapType_MapyTourist,
//    tile_mapType_HikeBike,
//    tile_mapType_Watercolor,
//    tile_mapType_Dark,
//    tile_mapType_Comic,
     
//    ui_header_baseMaps,
//    ui_header_drawingLegend,
//    ui_header_layerLegend,
//}