<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>


  <ItemGroup>
    <None Remove="Assets\Cursors\MaptorCursorSet\DrawPoint.cur" />
    <None Remove="Assets\Cursors\MaptorCursorSet\information.cur" />
    <None Remove="Assets\Cursors\MaptorCursorSet\ZoomIn.cur" />
    <None Remove="Assets\Cursors\MaptorCursorSet\ZoomOut.cur" />
    <None Remove="Assets\Fonts\IRANSans.ttf" />
    <None Remove="Assets\Images\BaseMaps\72\bingHybrid72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\bingSatellite72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\bingStreet72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\cartoDark72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\cartoLight72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\googleBlackWhite72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\googleGrey72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\googleHybrid72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\googleLight72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\googleNature72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\googleNeutralBlue72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\googleRoadMap72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\googleSatellite72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\googleTerrain72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\googleTraffic72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\mapboxComic72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\osmHikeBike72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\osmMapyTourist72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\osmMapyWinter72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\osmOpenStreetMap72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\osmOpenTopoMap72.jpg" />
    <None Remove="Assets\Images\BaseMaps\72\wazeStreet72.jpg" />
    <None Remove="Assets\Images\BaseMaps\bingHybrid.jpg" />
    <None Remove="Assets\Images\BaseMaps\bingSatellite.jpg" />
    <None Remove="Assets\Images\BaseMaps\bingSatellite.png" />
    <None Remove="Assets\Images\BaseMaps\bingStreet.jpg" />
    <None Remove="Assets\Images\BaseMaps\cartoDark.jpg" />
    <None Remove="Assets\Images\BaseMaps\cartoLight.jpg" />
    <None Remove="Assets\Images\BaseMaps\googleHybrid.jpg" />
    <None Remove="Assets\Images\BaseMaps\googleRoadmap.jpg" />
    <None Remove="Assets\Images\BaseMaps\googleSatellite.jpg" />
    <None Remove="Assets\Images\BaseMaps\googleTerrain.png" />
    <None Remove="Assets\Images\BaseMaps\mapyTourism.jpg" />
    <None Remove="Assets\Images\BaseMaps\mapyWinter.jpg" />
    <None Remove="Assets\Images\BaseMaps\openStreetMap.png" />
    <None Remove="Assets\Images\BaseMaps\openTopoMap.png" />
    <None Remove="Assets\Images\BaseMaps\osmHikeBike.jpg" />
    <None Remove="Assets\Images\BaseMaps\stamenWatercolor.jpg" />
    <None Remove="Assets\Images\BaseMaps\Waze.png" />
    <None Remove="Assets\Images\imageNotFound.jpg" />
    <None Remove="Assets\Images\Logos\google.png" />
    <None Remove="Properties\Resources.resx~RF2341c1.TMP" />
    <None Remove="Views\Map\SketchBarView.xaml~RF205a3a.TMP" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Images\Logos\google.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DataGridExtensions" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
    <PackageReference Include="Stateless" />
    <PackageReference Include="System.Data.SqlClient" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="WriteableBitmapEx" />
    <PackageReference Include="MahApps.Metro" />
    <PackageReference Include="MahApps.Metro.IconPacks.Modern" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" />
    <PackageReference Include="MahApps.Metro.IconPacks.PhosphorIcons" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\IRI.Maptor.Ket\IRI.Maptor.Ket.GdiPlus\IRI.Maptor.Ket.GdiPlus.csproj" />
    <!--<ProjectReference Include="..\..\IRI.Maptor.Ket\IRI.Maptor.Ket.SqlServerSpatialExtension\IRI.Maptor.Ket.SqlServerSpatialExtension.csproj" />-->
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.Common\IRI.Maptor.Sta.Common.csproj" />
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.MachineLearning\IRI.Maptor.Sta.MachineLearning.csproj" />
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.Ogc\IRI.Maptor.Sta.Ogc.csproj" />
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.Persistence\IRI.Maptor.Sta.Persistence.csproj" />
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.Pdf\IRI.Maptor.Sta.Pdf.csproj" />
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.Security\IRI.Maptor.Sta.Security.csproj" />
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.ShapefileFormat\IRI.Maptor.Sta.ShapefileFormat.csproj" />
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.Spatial\IRI.Maptor.Sta.Spatial.csproj" />
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.SpatialReferenceSystem\IRI.Maptor.Sta.SpatialReferenceSystem.csproj" />
  </ItemGroup>
 

  <ItemGroup>
    <Resource Include="Assets\Cursors\MaptorCursorSet\DrawPoint.cur" />
    <Resource Include="Assets\Cursors\MaptorCursorSet\information.cur" />
    <Resource Include="Assets\Cursors\MaptorCursorSet\ZoomIn.cur" />
    <Resource Include="Assets\Cursors\MaptorCursorSet\ZoomOut.cur" />
    <Resource Include="Assets\Fonts\IRANSans.ttf" />
    <Resource Include="Assets\Images\BaseMaps\72\bingHybrid72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\bingSatellite72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\bingStreet72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\cartoDark72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\cartoLight72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\googleBlackWhite72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\googleGrey72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\googleHybrid72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\googleLight72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\googleNature72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\googleNeutralBlue72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\googleRoadMap72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\googleSatellite72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\googleTerrain72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\googleTraffic72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\mapboxComic72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\osmHikeBike72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\osmMapyTourist72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\osmMapyWinter72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\osmOpenStreetMap72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\osmOpenTopoMap72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\72\wazeStreet72.jpg" />
    <Resource Include="Assets\Images\BaseMaps\bingHybrid.jpg" />
    <Resource Include="Assets\Images\BaseMaps\bingSatellite.jpg" />
    <Resource Include="Assets\Images\BaseMaps\bingSatellite.png" />
    <Resource Include="Assets\Images\BaseMaps\bingStreet.jpg" />
    <Resource Include="Assets\Images\BaseMaps\cartoDark.jpg" />
    <Resource Include="Assets\Images\BaseMaps\cartoLight.jpg" />
    <Resource Include="Assets\Images\BaseMaps\googleHybrid.jpg" />
    <Resource Include="Assets\Images\BaseMaps\googleRoadmap.jpg" />
    <Resource Include="Assets\Images\BaseMaps\googleSatellite.jpg" />
    <Resource Include="Assets\Images\BaseMaps\googleTerrain.png" />
    <Resource Include="Assets\Images\BaseMaps\mapyTourism.jpg" />
    <Resource Include="Assets\Images\BaseMaps\mapyWinter.jpg" />
    <Resource Include="Assets\Images\BaseMaps\openStreetMap.png" />
    <Resource Include="Assets\Images\BaseMaps\openTopoMap.png" />
    <Resource Include="Assets\Images\BaseMaps\osmHikeBike.jpg" />
    <Resource Include="Assets\Images\BaseMaps\stamenWatercolor.jpg" />
    <Resource Include="Assets\Images\BaseMaps\Waze.png" />
    <Resource Include="Assets\Images\Flags\us.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\ir.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\sa.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\fr.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\es.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\tr.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\ru.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\az.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\am.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\it.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\iq.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\br.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\in.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\cn.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Flags\pk.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\imageNotFound.jpg" />
    <Resource Include="Assets\Images\whiteImage.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\Dialogs\LayerSettingsDialogView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\General\FeatureTabControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\LayerSettings\LayerSettings_ExportView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\LayerSettings\LayerSettings_GeneralView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Localization\LanguageCombo.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Map\MapViewer.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.az.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.es.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.fa-IR.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.hy.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.it.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.ku-Arab-IQ.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.pt.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.ru.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.tr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.hi.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.zh-CN.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.ur.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Cartography\Symbologies\Decorators\" />
    <Folder Include="Cartography\Symbologies\Factories\" />
  </ItemGroup>
  
  <ItemGroup>
    <AssemblyAttribute Include="System.Windows.ThemeInfo">
      <_Parameter1>None</_Parameter1>
      <_Parameter2>SourceAssembly</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
  
  <ItemGroup>
    <Page Update="Assets\Styles\Controls.Path.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
</Project>
