<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="View\Map\Auxilary\**" />
    <EmbeddedResource Remove="View\Map\Auxilary\**" />
    <None Remove="View\Map\Auxilary\**" />
    <Page Remove="View\Map\Auxilary\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Images\transparentBackground.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DataGridExtensions" />
    <PackageReference Include="MahApps.Metro" />
    <PackageReference Include="MahApps.Metro.IconPacks.Modern" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" />
  </ItemGroup>
 
  <ItemGroup>
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.Common\IRI.Maptor.Sta.Common.csproj" />
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.Ogc\IRI.Maptor.Sta.Ogc.csproj" />
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.Persistence\IRI.Maptor.Sta.Persistence.csproj" />
    <ProjectReference Include="..\..\IRI.Maptor.Sta\IRI.Maptor.Sta.ShapefileFormat\IRI.Maptor.Sta.ShapefileFormat.csproj" />
    <ProjectReference Include="..\IRI.Maptor.Jab.Common\IRI.Maptor.Jab.Common.csproj" />
  </ItemGroup>
 
  <ItemGroup>
    <Resource Include="Assets\Images\transparentBackground.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="View\Map\MapViewer.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="View\Symbology\Sld\" />
  </ItemGroup>

</Project>
