<Project>
  <PropertyGroup>
    <Version>2.11.0</Version>
    <PackageIcon>package-icon.png</PackageIcon>
    <PackageIconUrl/>
    <PackageProjectUrl>https://github.com/hosseinnarimanirad/Maptor</PackageProjectUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)assets/images/package-icon.png"
			    Pack="true" 
			    PackagePath="\" 
			    Visible="false" />
  </ItemGroup>
</Project>
