<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <NoWarn>CS8602,CS8618,CS8625</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>Hossein Narimani Rad</Authors>
    <Company>Maptor</Company>
    <Description>A .NET standard library for GeoParquet format support (read/write geospatial vector data in Parquet format)</Description>
    <RepositoryUrl>https://github.com/hosseinnarimanirad/Maptor/tree/master/src/IRI.Maptor.Sta/IRI.Maptor.Sta.GeoParquet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>geometry;GIS;spatial;GeoParquet;Parquet;geospatial</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IRI.Maptor.Sta.Spatial\IRI.Maptor.Sta.Spatial.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Parquet.Net" />
  </ItemGroup>

</Project>

