using System;
using System.Collections.Generic;

using IRI.Maptor.Core.Common.Primitives;

namespace IRI.Maptor.Core.Spatial.Helpers.MapGrids;

/// <summary>
/// Walks one projection plane and emits the grid lines that cross a view — the shared body of
/// both metric schemes.
/// </summary>
/// <remarks>
/// <para>
/// A projected grid and a UTM grid are the same operation; UTM just runs it once per zone strip
/// and hemisphere, with the clip box narrowed to the strip. Keeping the walk in one place is what
/// makes the zone seam a property of <em>where UTM calls this</em> rather than a special case
/// buried inside it.
/// </para>
/// <para>
/// Each line is generated by stepping along the plane's other axis, inverting every sample to
/// geodetic, and clipping the result to the view. Sampling is necessary because a line of constant
/// easting is a curve on the map: straight in the projection, bowed in Web Mercator.
/// </para>
/// </remarks>
internal static class MapGridPlaneWalker
{
    /// <summary>
    /// Emits the major and minor lines of one plane into <paramref name="lines"/>, with their
    /// values placed by <paramref name="placer"/>.
    /// </summary>
    /// <param name="clipBox">The geodetic box lines are cut to — the view, narrowed to a zone strip for UTM.</param>
    /// <param name="plane">The range the clip box occupies in this plane.</param>
    /// <param name="inverse">Plane coordinates to WGS84 geodetic degrees.</param>
    /// <param name="major">The interval of the numbered lines, in metres.</param>
    /// <param name="minor">The subdivision interval, or null for none.</param>
    /// <param name="zone">The UTM zone these lines belong to, or null for a single-plane grid.</param>
    /// <param name="groupKey">Identifies the numbering run; per zone and hemisphere for UTM.</param>
    /// <param name="options">The engine's knobs.</param>
    /// <param name="lines">Collects the lines produced.</param>
    /// <param name="placer">Collects the values written against the edges.</param>
    internal static void Walk(
        BoundingBox clipBox,
        BoundingBox plane,
        Func<Point, Point> inverse,
        double major,
        double? minor,
        int? zone,
        string groupKey,
        MapGridOptions options,
        List<MapGridLine> lines,
        MapGridLabelPlacer placer)
    {
        if (plane.IsNaN() || !plane.IsValid() || major <= 0)
            return;

        // Major lines first, so that a truncated result still carries the ones that matter and
        // their values, rather than a screenful of unnumbered subdivisions.
        WalkAxis(MapGridAxis.X, MapGridLineKind.Major, major, clipBox, plane, inverse, zone, groupKey, major, options, lines, placer);
        WalkAxis(MapGridAxis.Y, MapGridLineKind.Major, major, clipBox, plane, inverse, zone, groupKey, major, options, lines, placer);

        if (!minor.HasValue || !options.ShowMinorLines)
            return;

        WalkAxis(MapGridAxis.X, MapGridLineKind.Minor, minor.Value, clipBox, plane, inverse, zone, groupKey, major, options, lines, placer);
        WalkAxis(MapGridAxis.Y, MapGridLineKind.Minor, minor.Value, clipBox, plane, inverse, zone, groupKey, major, options, lines, placer);
    }

    private static void WalkAxis(
        MapGridAxis axis,
        MapGridLineKind kind,
        double step,
        BoundingBox clipBox,
        BoundingBox plane,
        Func<Point, Point> inverse,
        int? zone,
        string groupKey,
        double major,
        MapGridOptions options,
        List<MapGridLine> lines,
        MapGridLabelPlacer placer)
    {
        var from = axis == MapGridAxis.X ? plane.XMin : plane.YMin;
        var to = axis == MapGridAxis.X ? plane.XMax : plane.YMax;

        var alongFrom = axis == MapGridAxis.X ? plane.YMin : plane.XMin;
        var alongTo = axis == MapGridAxis.X ? plane.YMax : plane.XMax;

        var first = Math.Ceiling(from / step) * step;

        var count = (int)Math.Floor((to - first) / step) + 1;

        if (count <= 0)
            return;

        // Guard before the loop rather than inside it: it is the count that could be enormous when
        // a fixed interval meets a continental view, and building 100 000 lines to throw them away
        // is the failure mode worth avoiding.
        if (count > options.MaxLines * 4)
            return;

        var samples = Math.Max(2, options.SamplesPerLine);

        for (var i = 0; i < count; i++)
        {
            if (lines.Count >= options.MaxLines)
                return;

            // Indexed rather than accumulated, so a long run does not drift off the round value.
            var value = first + i * step;

            if (kind == MapGridLineKind.Minor && IsMultipleOf(value, major))
                continue;

            var geodetic = new List<Point>(samples + 1);

            for (var j = 0; j <= samples; j++)
            {
                var along = alongFrom + (alongTo - alongFrom) * j / samples;

                var planePoint = axis == MapGridAxis.X ? new Point(value, along) : new Point(along, value);

                geodetic.Add(inverse(planePoint));
            }

            var parts = MapGridGeometry.ClipToBox(geodetic, clipBox);

            if (parts.Count == 0)
                continue;

            foreach (var part in parts)
            {
                lines.Add(new MapGridLine(axis, kind, value, MapGridGeometry.ToWebMercator(part), zone));

                if (lines.Count >= options.MaxLines)
                    break;
            }

            var text = MapGridLabelFormatter.FormatMetric(value);

            // highPart 0 for every line: a metric value is written out in full on every line, so
            // there is no abbreviated form for a rollover to interrupt. IsFull then marks simply
            // the first value written on each edge.
            placer.Place(parts, axis, kind, value, zone, highPart: 0, _ => text, groupKey);
        }
    }

    /// <summary>
    /// Whether a minor value lands on a major line, so it can be skipped rather than drawn twice —
    /// once light and once heavy, in whichever order the renderer happens to pick.
    /// </summary>
    internal static bool IsMultipleOf(double value, double interval)
    {
        if (interval <= 0)
            return false;

        var ratio = value / interval;

        var rounded = Math.Round(ratio);

        return Math.Abs(ratio - rounded) < 1e-9 * Math.Max(1.0, Math.Abs(rounded));
    }
}
