//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRI.Maptor.Jab.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRI.Maptor.Jab.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GeoJson.
        /// </summary>
        public static string cmd_drawingLegend_addGeoJson {
            get {
                return ResourceManager.GetString("cmd_drawingLegend_addGeoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lat/Long Text.
        /// </summary>
        public static string cmd_drawingLegend_addLatLongTxt {
            get {
                return ResourceManager.GetString("cmd_drawingLegend_addLatLongTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shapefile.
        /// </summary>
        public static string cmd_drawingLegend_addShapefile {
            get {
                return ResourceManager.GetString("cmd_drawingLegend_addShapefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string cmd_drawingLegend_moveDown {
            get {
                return ResourceManager.GetString("cmd_drawingLegend_moveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string cmd_drawingLegend_moveUp {
            get {
                return ResourceManager.GetString("cmd_drawingLegend_moveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all.
        /// </summary>
        public static string cmd_drawingLegend_removeAll {
            get {
                return ResourceManager.GetString("cmd_drawingLegend_removeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary.
        /// </summary>
        public static string cmd_drawingLegendItem_boundary {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_boundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Into Geometries.
        /// </summary>
        public static string cmd_drawingLegendItem_breakIntoGeometries {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_breakIntoGeometries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Into Points.
        /// </summary>
        public static string cmd_drawingLegendItem_breakIntoPoints {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_breakIntoPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convex Hull.
        /// </summary>
        public static string cmd_drawingLegendItem_convexHull {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_convexHull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download images.
        /// </summary>
        public static string cmd_drawingLegendItem_downloadRegionImages {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_downloadRegionImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string cmd_drawingLegendItem_duplicateFeature {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_duplicateFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string cmd_drawingLegendItem_edit {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope.
        /// </summary>
        public static string cmd_drawingLegendItem_envelope {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_envelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as GeoJson.
        /// </summary>
        public static string cmd_drawingLegendItem_exportAsGeoJson {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_exportAsGeoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as png.
        /// </summary>
        public static string cmd_drawingLegendItem_exportAsPng {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_exportAsPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as shapefile.
        /// </summary>
        public static string cmd_drawingLegendItem_exportAsShapefile {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_exportAsShapefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior ring.
        /// </summary>
        public static string cmd_drawingLegendItem_exteriorRing {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_exteriorRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove feature.
        /// </summary>
        public static string cmd_drawingLegendItem_remove {
            get {
                return ResourceManager.GetString("cmd_drawingLegendItem_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shapefile.
        /// </summary>
        public static string cmd_general_addShapefile {
            get {
                return ResourceManager.GetString("cmd_general_addShapefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Text.
        /// </summary>
        public static string cmd_general_addTextToMap {
            get {
                return ResourceManager.GetString("cmd_general_addTextToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string cmd_general_clearAll {
            get {
                return ResourceManager.GetString("cmd_general_clearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Point.
        /// </summary>
        public static string cmd_general_drawPoint {
            get {
                return ResourceManager.GetString("cmd_general_drawPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Polygon.
        /// </summary>
        public static string cmd_general_drawPolygon {
            get {
                return ResourceManager.GetString("cmd_general_drawPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Polyline.
        /// </summary>
        public static string cmd_general_drawPolyline {
            get {
                return ResourceManager.GetString("cmd_general_drawPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full extent.
        /// </summary>
        public static string cmd_general_fullExtent {
            get {
                return ResourceManager.GetString("cmd_general_fullExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To.
        /// </summary>
        public static string cmd_general_goTo {
            get {
                return ResourceManager.GetString("cmd_general_goTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure area.
        /// </summary>
        public static string cmd_general_measureArea {
            get {
                return ResourceManager.GetString("cmd_general_measureArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure length.
        /// </summary>
        public static string cmd_general_measureLength {
            get {
                return ResourceManager.GetString("cmd_general_measureLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        public static string cmd_general_pan {
            get {
                return ResourceManager.GetString("cmd_general_pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string cmd_general_zoomIn {
            get {
                return ResourceManager.GetString("cmd_general_zoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom next.
        /// </summary>
        public static string cmd_general_zoomNext {
            get {
                return ResourceManager.GetString("cmd_general_zoomNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string cmd_general_zoomOut {
            get {
                return ResourceManager.GetString("cmd_general_zoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom previous.
        /// </summary>
        public static string cmd_general_zoomPrevious {
            get {
                return ResourceManager.GetString("cmd_general_zoomPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GeoJson.
        /// </summary>
        public static string cmd_legend_addGeoJson {
            get {
                return ResourceManager.GetString("cmd_legend_addGeoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add lat/long.
        /// </summary>
        public static string cmd_legend_addLatLongTxt {
            get {
                return ResourceManager.GetString("cmd_legend_addLatLongTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add shapefile.
        /// </summary>
        public static string cmd_legend_addShapefile {
            get {
                return ResourceManager.GetString("cmd_legend_addShapefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string cmd_legend_moveDown {
            get {
                return ResourceManager.GetString("cmd_legend_moveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string cmd_legend_moveUp {
            get {
                return ResourceManager.GetString("cmd_legend_moveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string cmd_legend_removeAll {
            get {
                return ResourceManager.GetString("cmd_legend_removeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selected Features.
        /// </summary>
        public static string cmd_legendItem_clearSelected {
            get {
                return ResourceManager.GetString("cmd_legendItem_clearSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as GeoJson.
        /// </summary>
        public static string cmd_legendItem_exportAsGeoJson {
            get {
                return ResourceManager.GetString("cmd_legendItem_exportAsGeoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as png.
        /// </summary>
        public static string cmd_legendItem_exportAsPng {
            get {
                return ResourceManager.GetString("cmd_legendItem_exportAsPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as shapefile.
        /// </summary>
        public static string cmd_legendItem_exportAsShapefile {
            get {
                return ResourceManager.GetString("cmd_legendItem_exportAsShapefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove layer.
        /// </summary>
        public static string cmd_legendItem_remove {
            get {
                return ResourceManager.GetString("cmd_legendItem_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by drawing.
        /// </summary>
        public static string cmd_legendItem_selectByDrawing {
            get {
                return ResourceManager.GetString("cmd_legendItem_selectByDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show attributes.
        /// </summary>
        public static string cmd_legendItem_showAttributes {
            get {
                return ResourceManager.GetString("cmd_legendItem_showAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Symbology.
        /// </summary>
        public static string cmd_legendItem_showSymbology {
            get {
                return ResourceManager.GetString("cmd_legendItem_showSymbology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Layer Label.
        /// </summary>
        public static string cmd_legendItem_toggleLayerLabel {
            get {
                return ResourceManager.GetString("cmd_legendItem_toggleLayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To Extent.
        /// </summary>
        public static string cmd_legendItem_zoomToExtent {
            get {
                return ResourceManager.GetString("cmd_legendItem_zoomToExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan to.
        /// </summary>
        public static string dialog_goto_panTo {
            get {
                return ResourceManager.GetString("dialog_goto_panTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To.
        /// </summary>
        public static string dialog_goto_title {
            get {
                return ResourceManager.GetString("dialog_goto_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to.
        /// </summary>
        public static string dialog_goto_zoomTo {
            get {
                return ResourceManager.GetString("dialog_goto_zoomTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string dialog_symbology_fill {
            get {
                return ResourceManager.GetString("dialog_symbology_fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke.
        /// </summary>
        public static string dialog_symbology_stroke {
            get {
                return ResourceManager.GetString("dialog_symbology_stroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke width.
        /// </summary>
        public static string dialog_symbology_strokeWidth {
            get {
                return ResourceManager.GetString("dialog_symbology_strokeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Symbology.
        /// </summary>
        public static string dialog_symbology_title {
            get {
                return ResourceManager.GetString("dialog_symbology_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imageNotFound {
            get {
                object obj = ResourceManager.GetObject("imageNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index 100k.
        /// </summary>
        public static string index_100k_title {
            get {
                return ResourceManager.GetString("index_100k_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index 10k.
        /// </summary>
        public static string index_10k_title {
            get {
                return ResourceManager.GetString("index_10k_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index 1000.
        /// </summary>
        public static string index_1kUtm_title {
            get {
                return ResourceManager.GetString("index_1kUtm_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index 250k.
        /// </summary>
        public static string index_250k_title {
            get {
                return ResourceManager.GetString("index_250k_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index 25k.
        /// </summary>
        public static string index_25k_title {
            get {
                return ResourceManager.GetString("index_25k_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index 2000 Blocks.
        /// </summary>
        public static string index_2kblocks_title {
            get {
                return ResourceManager.GetString("index_2kblocks_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index 2000.
        /// </summary>
        public static string index_2kUtm_title {
            get {
                return ResourceManager.GetString("index_2kUtm_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index 500.
        /// </summary>
        public static string index_500UtmTitle {
            get {
                return ResourceManager.GetString("index_500UtmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index 50k.
        /// </summary>
        public static string index_50k_title {
            get {
                return ResourceManager.GetString("index_50k_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index 5k.
        /// </summary>
        public static string index_5k_title {
            get {
                return ResourceManager.GetString("index_5k_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodesy 1.
        /// </summary>
        public static string layer_geodesy1_title {
            get {
                return ResourceManager.GetString("layer_geodesy1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodesy 2.
        /// </summary>
        public static string layer_geodesy2_title {
            get {
                return ResourceManager.GetString("layer_geodesy2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodynamics.
        /// </summary>
        public static string layer_geodynamics_title {
            get {
                return ResourceManager.GetString("layer_geodynamics_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravimetry.
        /// </summary>
        public static string layer_gravimetry_title {
            get {
                return ResourceManager.GetString("layer_gravimetry_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveling 1.
        /// </summary>
        public static string layer_leveling1_title {
            get {
                return ResourceManager.GetString("layer_leveling1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveling 2.
        /// </summary>
        public static string layer_leveling2_title {
            get {
                return ResourceManager.GetString("layer_leveling2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveling 3.
        /// </summary>
        public static string layer_leveling3_title {
            get {
                return ResourceManager.GetString("layer_leveling3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Level.
        /// </summary>
        public static string map_coordinatePanel_zoomLevel {
            get {
                return ResourceManager.GetString("map_coordinatePanel_zoomLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Point.
        /// </summary>
        public static string map_draw_addPoint {
            get {
                return ResourceManager.GetString("map_draw_addPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Drawing.
        /// </summary>
        public static string map_draw_cancelDrawing {
            get {
                return ResourceManager.GetString("map_draw_cancelDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Drawing.
        /// </summary>
        public static string map_draw_finishDrawing {
            get {
                return ResourceManager.GetString("map_draw_finishDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Drawing Part.
        /// </summary>
        public static string map_draw_finishDrawingPart {
            get {
                return ResourceManager.GetString("map_draw_finishDrawingPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the last point to finish drawing..
        /// </summary>
        public static string map_draw_newDrawing {
            get {
                return ResourceManager.GetString("map_draw_newDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string map_scale_content {
            get {
                return ResourceManager.GetString("map_scale_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new part.
        /// </summary>
        public static string mapPanel_currentPart_add {
            get {
                return ResourceManager.GetString("mapPanel_currentPart_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current part.
        /// </summary>
        public static string mapPanel_currentPart_delete {
            get {
                return ResourceManager.GetString("mapPanel_currentPart_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to current part.
        /// </summary>
        public static string mapPanel_currentPart_zoom {
            get {
                return ResourceManager.GetString("mapPanel_currentPart_zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy current point&apos;s coordinate.
        /// </summary>
        public static string mapPanel_currentPoint_copyCoordinate {
            get {
                return ResourceManager.GetString("mapPanel_currentPoint_copyCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current point.
        /// </summary>
        public static string mapPanel_currentPoint_delete {
            get {
                return ResourceManager.GetString("mapPanel_currentPoint_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Coordinates.
        /// </summary>
        public static string mapPanel_currentPoint_displayCoordinate {
            get {
                return ResourceManager.GetString("mapPanel_currentPoint_displayCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next point.
        /// </summary>
        public static string mapPanel_currentPoint_goToNextPoint {
            get {
                return ResourceManager.GetString("mapPanel_currentPoint_goToNextPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous point.
        /// </summary>
        public static string mapPanel_currentPoint_goToPreviousPoint {
            get {
                return ResourceManager.GetString("mapPanel_currentPoint_goToPreviousPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to current point.
        /// </summary>
        public static string mapPanel_currentPoint_zoom {
            get {
                return ResourceManager.GetString("mapPanel_currentPoint_zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Edit.
        /// </summary>
        public static string mapPanel_edit_cancel {
            get {
                return ResourceManager.GetString("mapPanel_edit_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string mapPanel_edit_delete {
            get {
                return ResourceManager.GetString("mapPanel_edit_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Edit.
        /// </summary>
        public static string mapPanel_edit_finish {
            get {
                return ResourceManager.GetString("mapPanel_edit_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Point.
        /// </summary>
        public static string mapPanel_header_currentPoint {
            get {
                return ResourceManager.GetString("mapPanel_header_currentPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        public static string mapPanel_header_measure {
            get {
                return ResourceManager.GetString("mapPanel_header_measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi part.
        /// </summary>
        public static string mapPanel_header_multiPart {
            get {
                return ResourceManager.GetString("mapPanel_header_multiPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Reference System.
        /// </summary>
        public static string mapPanel_header_srs {
            get {
                return ResourceManager.GetString("mapPanel_header_srs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to drawing item.
        /// </summary>
        public static string mapPanel_measure_convertToDrawing {
            get {
                return ResourceManager.GetString("mapPanel_measure_convertToDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Edge Labels.
        /// </summary>
        public static string mapPanel_measure_showEdgeLabels {
            get {
                return ResourceManager.GetString("mapPanel_measure_showEdgeLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing.
        /// </summary>
        public static string ribbon_header_drawing {
            get {
                return ResourceManager.GetString("ribbon_header_drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ribbon_header_help {
            get {
                return ResourceManager.GetString("ribbon_header_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string ribbon_header_map {
            get {
                return ResourceManager.GetString("ribbon_header_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ribbon_header_settings {
            get {
                return ResourceManager.GetString("ribbon_header_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylindrical Equal Area.
        /// </summary>
        public static string srs_ceaSubTitle {
            get {
                return ResourceManager.GetString("srs_ceaSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylindrical Equal Area.
        /// </summary>
        public static string srs_ceaTitle {
            get {
                return ResourceManager.GetString("srs_ceaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        public static string srs_defaultLatitude {
            get {
                return ResourceManager.GetString("srs_defaultLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        public static string srs_defaultLongitude {
            get {
                return ResourceManager.GetString("srs_defaultLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        public static string srs_defaultX {
            get {
                return ResourceManager.GetString("srs_defaultX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        public static string srs_defaultY {
            get {
                return ResourceManager.GetString("srs_defaultY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic, WGS84.
        /// </summary>
        public static string srs_geodeticDmsSubTitle {
            get {
                return ResourceManager.GetString("srs_geodeticDmsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic, WGS84 (dms).
        /// </summary>
        public static string srs_geodeticDmsTitle {
            get {
                return ResourceManager.GetString("srs_geodeticDmsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic, WGS84.
        /// </summary>
        public static string srs_geodeticSubTitle {
            get {
                return ResourceManager.GetString("srs_geodeticSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic, WGS84 (decimal degree).
        /// </summary>
        public static string srs_geodeticTitle {
            get {
                return ResourceManager.GetString("srs_geodeticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercator.
        /// </summary>
        public static string srs_mercatorSubTitle {
            get {
                return ResourceManager.GetString("srs_mercatorSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercator.
        /// </summary>
        public static string srs_mercatorTitle {
            get {
                return ResourceManager.GetString("srs_mercatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transeverse Mercator.
        /// </summary>
        public static string srs_tmSubTitle {
            get {
                return ResourceManager.GetString("srs_tmSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transeverse Mercator.
        /// </summary>
        public static string srs_tmTitle {
            get {
                return ResourceManager.GetString("srs_tmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM.
        /// </summary>
        public static string srs_utmSubTitle {
            get {
                return ResourceManager.GetString("srs_utmSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Transeverse Mercator (UTM).
        /// </summary>
        public static string srs_utmTitle {
            get {
                return ResourceManager.GetString("srs_utmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string srs_utmZone {
            get {
                return ResourceManager.GetString("srs_utmZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Mercator.
        /// </summary>
        public static string srs_webMercatorSubTitle {
            get {
                return ResourceManager.GetString("srs_webMercatorSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Mercator.
        /// </summary>
        public static string srs_webMercatorTitle {
            get {
                return ResourceManager.GetString("srs_webMercatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlackWhite.
        /// </summary>
        public static string tile_mapType_BlackWhite {
            get {
                return ResourceManager.GetString("tile_mapType_BlackWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CleanGrey.
        /// </summary>
        public static string tile_mapType_CleanGrey {
            get {
                return ResourceManager.GetString("tile_mapType_CleanGrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic.
        /// </summary>
        public static string tile_mapType_Comic {
            get {
                return ResourceManager.GetString("tile_mapType_Comic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string tile_mapType_Dark {
            get {
                return ResourceManager.GetString("tile_mapType_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HikeBike.
        /// </summary>
        public static string tile_mapType_HikeBike {
            get {
                return ResourceManager.GetString("tile_mapType_HikeBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string tile_mapType_Hybrid {
            get {
                return ResourceManager.GetString("tile_mapType_Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string tile_mapType_Light {
            get {
                return ResourceManager.GetString("tile_mapType_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapyTourist.
        /// </summary>
        public static string tile_mapType_MapyTourist {
            get {
                return ResourceManager.GetString("tile_mapType_MapyTourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapyWinter.
        /// </summary>
        public static string tile_mapType_MapyWinter {
            get {
                return ResourceManager.GetString("tile_mapType_MapyWinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature.
        /// </summary>
        public static string tile_mapType_Nature {
            get {
                return ResourceManager.GetString("tile_mapType_Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NeutralBlue.
        /// </summary>
        public static string tile_mapType_NeutralBlue {
            get {
                return ResourceManager.GetString("tile_mapType_NeutralBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoadMap.
        /// </summary>
        public static string tile_mapType_RoadMap {
            get {
                return ResourceManager.GetString("tile_mapType_RoadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        public static string tile_mapType_Satellite {
            get {
                return ResourceManager.GetString("tile_mapType_Satellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string tile_mapType_Street {
            get {
                return ResourceManager.GetString("tile_mapType_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        public static string tile_mapType_Terrain {
            get {
                return ResourceManager.GetString("tile_mapType_Terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topo.
        /// </summary>
        public static string tile_mapType_Topo {
            get {
                return ResourceManager.GetString("tile_mapType_Topo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic.
        /// </summary>
        public static string tile_mapType_Traffic {
            get {
                return ResourceManager.GetString("tile_mapType_Traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watercolor.
        /// </summary>
        public static string tile_mapType_Watercolor {
            get {
                return ResourceManager.GetString("tile_mapType_Watercolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BING.
        /// </summary>
        public static string tile_provider_bing {
            get {
                return ResourceManager.GetString("tile_provider_bing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARTO.
        /// </summary>
        public static string tile_provider_carto {
            get {
                return ResourceManager.GetString("tile_provider_carto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOGLE.
        /// </summary>
        public static string tile_provider_google {
            get {
                return ResourceManager.GetString("tile_provider_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPBOX.
        /// </summary>
        public static string tile_provider_mapbox {
            get {
                return ResourceManager.GetString("tile_provider_mapbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOKIA.
        /// </summary>
        public static string tile_provider_nokia {
            get {
                return ResourceManager.GetString("tile_provider_nokia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPENSTREETMAP.
        /// </summary>
        public static string tile_provider_osm {
            get {
                return ResourceManager.GetString("tile_provider_osm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAZE.
        /// </summary>
        public static string tile_provider_waze {
            get {
                return ResourceManager.GetString("tile_provider_waze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YANDEX.
        /// </summary>
        public static string tile_provider_yandex {
            get {
                return ResourceManager.GetString("tile_provider_yandex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Maps.
        /// </summary>
        public static string ui_header_baseMaps {
            get {
                return ResourceManager.GetString("ui_header_baseMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawings.
        /// </summary>
        public static string ui_header_drawingLegend {
            get {
                return ResourceManager.GetString("ui_header_drawingLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string ui_header_layerLegend {
            get {
                return ResourceManager.GetString("ui_header_layerLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string wat_security_userName {
            get {
                return ResourceManager.GetString("wat_security_userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap whiteImage {
            get {
                object obj = ResourceManager.GetObject("whiteImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
