<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IRI.Maptor.Jab.Common\IRI.Maptor.Jab.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro" />
    <PackageReference Include="MahApps.Metro.IconPacks.Modern" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" />
  </ItemGroup>

</Project>
