using System;
using System.Linq;
using System.Windows;
using System.Windows.Media;
using System.ComponentModel;
using System.Runtime.CompilerServices;

using IRI.Maptor.Extensions;
using IRI.Maptor.Jab.Common.Events;
using IRI.Maptor.Jab.Common.Helpers;
using IRI.Maptor.Sta.Spatial.Primitives;
using IRI.Maptor.Jab.Common.Cartography.Symbologies;

using Sb = IRI.Maptor.Sta.Common.Primitives;
using IRI.Maptor.Jab.Core.Models;

namespace IRI.Maptor.Jab.Common;

public class VisualParameters : /*DependencyObject,*/ INotifyPropertyChanged
{
    //private event EventHandler<CustomEventArgs<Visibility>>? _onVisibilityChanged;

    //public event EventHandler<CustomEventArgs<Visibility>> OnVisibilityChanged
    //{
    //    remove { this._onVisibilityChanged -= value; }
    //    add
    //    {
    //        if (this._onVisibilityChanged == null)
    //            this._onVisibilityChanged += value;
    //    }
    //}

    //public event EventHandler<CustomEventArgs<VisualParameters>>? OnChanged;

    //public event EventHandler<CustomEventArgs<VisualParameters>>? OnIsInScaleRangeChanged;

    //public event EventHandler<CustomEventArgs<VisualParameters>>? OnIsOnChanged;


    #region General Properties

    private string _title = string.Empty;
    public string Title
    {
        get { return _title; }
        set
        {
            _title = value;
            RaisePropertyChanged();
        }
    }


    private ScaleInterval _visibleRange = ScaleInterval.All;
    public ScaleInterval VisibleRange
    {
        get { return _visibleRange; }
        set
        {
            _visibleRange = value;
            RaisePropertyChanged();
        }
    }


    private double _opacity = 1;
    public double Opacity
    {
        get { return _opacity; }
        set
        {
            _opacity = value;
            RaisePropertyChanged();
        }
    }


    private bool _isEnabled;
    public bool IsEnabled
    {
        get { return _isEnabled; }
        set
        {
            _isEnabled = value;
            RaisePropertyChanged();

            //this.OnChanged?.Invoke(this, new CustomEventArgs<VisualParameters>(this));

            //this.OnIsInScaleRangeChanged?.Invoke(this, new CustomEventArgs<VisualParameters>(this));
        }
    }


    private bool _isSelected;
    public bool IsSelected
    {
        get { return _isSelected; }
        set
        {
            _isSelected = value;
            RaisePropertyChanged();
            //OnIsOnChanged?.Invoke(this, new CustomEventArgs<VisualParameters>(this));
        }
    }

    //private Visibility _visibility;
    //public Visibility Visibility
    //{
    //    get { return _visibility; }
    //    set
    //    {
    //        if (_visibility == value)
    //            return;

    //        _visibility = value;
    //        RaisePropertyChanged();
    //        this._onVisibilityChanged?.Invoke(this, new CustomEventArgs<Visibility>(value));
    //    }
    //}

    #endregion


    #region Brush & Stroke Properties

    private Brush? _fill;
    public Brush? Fill
    {
        get { return _fill; }
        set
        {
            _fill = value;
            RaisePropertyChanged();
        }
    }


    private Brush? _stroke;
    public Brush? Stroke
    {
        get { return _stroke; }
        set
        {
            _stroke = value;
            RaisePropertyChanged();
        }
    }


    private double _strokeThickness;
    public double StrokeThickness
    {
        get { return _strokeThickness; }
        set
        {
            _strokeThickness = value;
            RaisePropertyChanged();
        }
    }


    private DashStyle _dashStyle = DashStyles.Solid;

    /// <summary>
    /// Gets or sets a value that describes the pattern of dashes generated by this Pen. 
    /// The default is Solid, which indicates that there should be no dashes.
    /// </summary>
    public DashStyle DashStyle
    {
        get { return _dashStyle; }
        set
        {
            _dashStyle = value;
            RaisePropertyChanged();
        }
    }

    /// <summary>
    /// The type of shape that starts the stroke. The default value is Flat.
    /// </summary>
    public PenLineCap PenStartLineCap { get; set; } = PenLineCap.Flat;

    /// <summary>
    /// The type of shape that ends the stroke. The default value is Flat.
    /// </summary>
    public PenLineCap PenEndLineCap { get; set; } = PenLineCap.Flat;

    // Gets or sets a value that specifies how the ends of each dash are drawn.
    // The default value is Square.
    public PenLineCap PenDashCap { get; set; } = PenLineCap.Square;

    /// <summary>
    /// The type of joint used at the vertices of a shape's outline. 
    /// The default value is Miter.
    /// Miter make sharp line joins to prevent it we use Round as default.
    /// </summary>
    public PenLineJoin PenLineJoin { get; set; } = PenLineJoin.Round;

    /// <summary>
    /// The limit on the ratio of the miter length to half the pen's Thickness. 
    /// This value is always a positive number greater than or equal to 1. 
    /// The default value is 10.0.
    /// </summary>
    public double PenMiterLimit { get; set; } = 10;

    #endregion


    #region Label Fields & Properties 

    public Func<Geometry<Sb.Point>, Sb.Point>? PositionFunc { get; set; }

    public bool HasLabelParameters => FontFamily != null || Foreground != null || Background != null;

    private int _fontSize;
    public int FontSize
    {
        get { return _fontSize; }
        set
        {
            _fontSize = value;
            RaisePropertyChanged();
        }
    }


    private Brush? _foreground;
    public Brush? Foreground
    {
        get { return _foreground; }
        set
        {
            _foreground = value;
            RaisePropertyChanged();
        }
    }


    private Brush? _background;
    public Brush? Background
    {
        get { return _background; }
        set
        {
            _background = value;
            RaisePropertyChanged();
        }
    }


    private FontFamily? _fontFamily;
    public FontFamily? FontFamily
    {
        get { return _fontFamily; }
        set
        {
            _fontFamily = value;
            RaisePropertyChanged();
        }
    }


    private bool _isRtl = true;
    public bool IsRtl
    {
        get { return _isRtl; }
        set
        {
            _isRtl = value;
            RaisePropertyChanged();
        }
    }

    #endregion


    private SimplePointSymbolizer _pointSymbol = new SimplePointSymbolizer() { SymbolWidth = 4, SymbolHeight = 4 };
    public SimplePointSymbolizer PointSymbol
    {
        get { return _pointSymbol; }
        set
        {
            _pointSymbol = value;
            RaisePropertyChanged();
        }
    }


    #region Old codes

    //private int _order;
    //public int Order
    //{
    //    get { return _order; }
    //    set
    //    {
    //        _order = value;
    //        RaisePropertyChanged();
    //    }
    //}


    //public Brush Fill
    //{
    //    get { return (Brush)GetValue(FillProperty); }
    //    set { SetValue(FillProperty, value); }
    //}

    //public static readonly DependencyProperty FillProperty =
    //    DependencyProperty.Register(nameof(Fill), typeof(Brush), typeof(VisualParameters), new PropertyMetadata());

    //public Brush Stroke
    //{
    //    get { return (Brush)GetValue(StrokeProperty); }
    //    set { SetValue(StrokeProperty, value); }
    //}

    //public static readonly DependencyProperty StrokeProperty =
    //    DependencyProperty.Register(nameof(Stroke), typeof(Brush), typeof(VisualParameters), new PropertyMetadata(null));

    //public double StrokeThickness
    //{
    //    get { return (double)GetValue(StrokeThicknessProperty); }
    //    set { SetValue(StrokeThicknessProperty, value); }
    //}

    //public static readonly DependencyProperty StrokeThicknessProperty =
    //    DependencyProperty.Register(nameof(StrokeThickness), typeof(double), typeof(VisualParameters));

    //public double Opacity
    //{
    //    get { return (double)GetValue(OpacityProperty); }
    //    set { SetValue(OpacityProperty, value); }
    //}

    //public static readonly DependencyProperty OpacityProperty =
    //    DependencyProperty.Register(nameof(Opacity), typeof(double), typeof(VisualParameters));

    //public Visibility Visibility
    //{
    //    get { return (Visibility)GetValue(VisibilityProperty); }
    //    set { SetValue(VisibilityProperty, value); }
    //}

    //public static readonly DependencyProperty VisibilityProperty =
    //    DependencyProperty.Register(nameof(Visibility),
    //                                typeof(Visibility),
    //                                typeof(VisualParameters),
    //                                new PropertyMetadata(Visibility.Visible, new PropertyChangedCallback((dp, dpE) =>
    //                                {
    //                                    var obj = dp as VisualParameters;

    //                                    if (obj is null)
    //                                        return;

    //                                    var newVisibility = (Visibility)dpE.NewValue;

    //                                    var oldVisibility = (Visibility)dpE.OldValue;

    //                                    if (newVisibility == oldVisibility) { }
    //                                    else
    //                                    {
    //                                        obj._onVisibilityChanged?.Invoke(obj, new CustomEventArgs<Visibility>(newVisibility));
    //                                    }
    //                                })));

    //public int Order
    //{
    //    get { return (int)GetValue(OrderProperty); }
    //    set { SetValue(OrderProperty, value); }
    //}

    //// Using a DependencyProperty as the backing store for Order.  This enables animation, styling, binding, etc...
    //public static readonly DependencyProperty OrderProperty =
    //    DependencyProperty.Register(nameof(Order), typeof(int), typeof(VisualParameters));


    //// ************************************* DashType *********************************************
    //public DoubleCollection DashType
    //{
    //    get { return (DoubleCollection)GetValue(DashTypeProperty); }
    //    set { SetValue(DashTypeProperty, value); }
    //}

    //public static readonly DependencyProperty DashTypeProperty =
    //    DependencyProperty.Register(nameof(DashType), typeof(DoubleCollection), typeof(VisualParameters));


    //public DashStyle DashStyle
    //{
    //    get { return (DashStyle)GetValue(DashStyleProperty); }
    //    set { SetValue(DashStyleProperty, value); }
    //}

    //public static readonly DependencyProperty DashStyleProperty =
    //    DependencyProperty.Register(nameof(DashStyle), typeof(DashStyle), typeof(VisualParameters), new PropertyMetadata(null));

    //public bool IsInScaleRange
    //{
    //    get { return (bool)GetValue(IsInScaleRangeProperty); }
    //    set { SetValue(IsInScaleRangeProperty, value); }
    //}

    //public static readonly DependencyProperty IsInScaleRangeProperty =
    //    DependencyProperty.Register(nameof(IsInScaleRange), typeof(bool), typeof(VisualParameters), new PropertyMetadata(true, new PropertyChangedCallback((dp, dpE) =>
    //{
    //    var obj = dp as VisualParameters;

    //    var newIsInScaleRange = ((bool)dpE.NewValue);

    //    var oldIsInScaleRange = ((bool)dpE.OldValue);

    //    if (newIsInScaleRange != oldIsInScaleRange)
    //    {
    //        obj.OnChanged?.Invoke(obj, new CustomEventArgs<VisualParameters>(obj));


    //        obj.OnIsInScaleRangeChanged?.Invoke(obj, new CustomEventArgs<VisualParameters>(obj));
    //    }
    //})));

    #endregion


    private VisualParameters() { }

    private VisualParameters(double opacity) : this(BrushHelper.PickBrush(), BrushHelper.PickBrush(), 1, opacity, isOn: true)
    {
    }

    public VisualParameters(Brush? fill, Brush? stroke, double strokeThickness, double opacity, bool isOn = true)
    {
        this.Fill = fill ?? Brushes.Transparent;

        this.Stroke = stroke;

        this.StrokeThickness = strokeThickness;

        this.Opacity = opacity;

        //this.Visibility = visibility;

        this.IsSelected = isOn;
    }

    public VisualParameters(Color fill, Color? stroke = null, double strokeThickness = 1, double opacity = 1)
        : this(new SolidColorBrush(fill), stroke.HasValue ? new SolidColorBrush(stroke.Value) : null, strokeThickness, opacity, isOn: true)
    {

    }

    public VisualParameters(string hexFill, string hexStroke, double strokeThickness = 1, double opacity = 1) :
        this(BrushHelper.CreateBrush(hexFill), BrushHelper.CreateBrush(hexStroke), strokeThickness, opacity, isOn: true)
    {

    }


    public bool IsInScaleRangeAndSelected(double inverseMapScale)
    {
        return VisibleRange.IsInRange(inverseMapScale) && IsSelected;
    }

    public bool IsInScaleRange(double inverseMapScale)
    {
        return VisibleRange.IsInRange(inverseMapScale);
    }

    public VisualParameters Clone()
    {
        return new VisualParameters(Fill, Stroke, StrokeThickness, Opacity, IsSelected);
    }

    // todo: check if necassary to apply the opacity
    public Pen? GetWpfPen()
    {
        var result = Stroke != null ? new Pen(Stroke, StrokeThickness) : null;

        if (result is null)
            return null;

        result.DashStyle = DashStyle;
        result.StartLineCap = PenStartLineCap;
        result.EndLineCap = PenEndLineCap;
        result.DashCap = PenDashCap;
        result.LineJoin = PenLineJoin;
        result.MiterLimit = PenMiterLimit;

        return result;
    }

    public System.Drawing.Pen? GetGdiPlusPen() => GetWpfPen().AsGdiPen();

    public System.Drawing.Brush? GetGdiPlusFillBrush(double? opacity = null) => Fill?.AsGdiBrush(opacity);


    #region Builders

    public void Build(Sta.Ogc.SLD.Stroke stroke)
    {
        if (stroke is null)
            return;

        var strokeValue = stroke.StrokeValue;
        var strokeThickness = stroke.StrokeThicknessValue;
        var strokeOpacity = stroke.StrokeOpacityValue;
        var strokeLineJoin = stroke.StrokeLineJoinValue;
        var strokeLineCap = stroke.StrokeLineCapValue;
        var strokeDashArray = stroke.StrokeDashArrayValue;
        var strokeDashOffset = stroke.StrokeDashOffsetValue;

        this.Stroke = BrushHelper.CreateBrush(strokeValue, strokeOpacity);
        this.StrokeThickness = strokeThickness;

        this.PenLineJoin = strokeLineJoin.Parse();
        this.PenDashCap = strokeLineCap.Parse();

        if (strokeDashArray is not null)
            this.DashStyle = new System.Windows.Media.DashStyle(strokeDashArray.ToList(), strokeDashOffset);

        return;
    }

    public void Build(Sta.Ogc.SLD.Fill fill)
    {
        if (fill is null)
            return;

        var fillValue = fill.FillValue;
        var fillOpacity = fill.FillOpacityValue;

        this.Fill = BrushHelper.CreateBrush(fillValue, fillOpacity);

    }

    public void MergeWithLabel(VisualParameters labelParameters)
    {
        this.FontFamily = labelParameters.FontFamily;
        this.FontSize = labelParameters.FontSize;
        this.Foreground = labelParameters.Foreground;
        this.PositionFunc = labelParameters.PositionFunc;
        this.IsRtl = labelParameters.IsRtl;
    }

    #endregion


    #region Static 

    /// <summary>
    /// Returns a random VisualParameters
    /// </summary>
    /// <param name="opacity"></param>
    /// <returns></returns>
    public static VisualParameters CreateNew(double opacity = 1) => new VisualParameters(opacity);

    public static VisualParameters CreateNew(double opacity, double strokeThickness = 1, bool withoutFill = false)
    {
        Brush? fill = null;

        if (!withoutFill)
        {
            fill = BrushHelper.PickGoodBrush();
        }

        return new VisualParameters(fill, BrushHelper.PickBrush(), strokeThickness, opacity, isOn: true);
    }

    public static VisualParameters CreateLabel(
        ScaleInterval visibleRange,
        int fontSize,
        Brush? foreground,
        FontFamily fontFamily,
        Func<Geometry<Sb.Point>, Sb.Point> positionFunc,
        bool isRtl)
    {
        return new VisualParameters()
        {
            VisibleRange = visibleRange,
            FontSize = fontSize,
            Foreground = foreground ?? Brushes.Black,
            FontFamily = fontFamily,
            PositionFunc = positionFunc,
            IsRtl = isRtl,            
        };//
    }

    public static VisualParameters GetFill(Color fill, double opacity = 1)
    {
        return new VisualParameters(new SolidColorBrush(fill), null, 0, opacity);
    }

    public static VisualParameters GetStroke(Color stroke, double strokeThickness = 1, double opacity = 1)
    {
        return new VisualParameters(null, new SolidColorBrush(stroke), strokeThickness, opacity);
    }

    public static VisualParameters GetFill(string? hexFill, double opacity = 1)
    {
        return new VisualParameters(new SolidColorBrush(ColorHelper.ToWpfColor(hexFill)), null, 0, opacity);
    }

    public static VisualParameters GetStroke(string? hexStroke, double strokeThickness = 1, double opacity = 1)
    {
        return new VisualParameters(null, new SolidColorBrush(ColorHelper.ToWpfColor(hexStroke)), strokeThickness, opacity);
    }

    public static VisualParameters Get(Color fill, Color stroke, double strokeThickness, double opacity = 1)
    {
        return new VisualParameters(new SolidColorBrush(fill), new SolidColorBrush(stroke), strokeThickness, opacity);
    }

    public static VisualParameters Get(string? hexFill, string? hexStroke, double strokeThickness, double fillOpacity = 1, double strokeOpacity = 1)
    {
        var fill = ColorHelper.ToWpfColor(hexFill, fillOpacity);

        var stroke = ColorHelper.ToWpfColor(hexStroke, strokeOpacity);

        return new VisualParameters(new SolidColorBrush(fill), new SolidColorBrush(stroke), strokeThickness, 1);
    }
   
    public static VisualParameters GetDefaultForSelection(double? strokeThickness)
    {
        return new VisualParameters(DefaultSelectionFill, DefaultSelectionStroke, strokeThickness ?? 2, 0.9);
    }

    public static VisualParameters GetDefaultForHighlight(double? strokeThickness)
    {
        return new VisualParameters(DefaultHighlightFill, DefaultHighlightStroke, strokeThickness ?? 3, .8);
    }

    public static VisualParameters GetDefaultForHighlight(Feature<Sb.Point> sqlGeometryAware, double? strokeThickness)
    {
        VisualParameters result;

        if (sqlGeometryAware?.TheGeometry?.IsPointOrMultiPoint() == true)
        { 
            result = new VisualParameters(DefaultHighlightStroke, DefaultHighlightFill, strokeThickness ?? 3, .9) { PointSymbol = new SimplePointSymbolizer(10) };
        }
        else
        {
            result = GetDefaultForHighlight(strokeThickness);
        }

        return result;

    }

    public static VisualParameters GetDefaultForRoutingPoints()
    {
        return new VisualParameters(DefaultRoutingPointFill, DefaultRoutingPointStroke, 2, 0.9);
    }

    public static VisualParameters GetDefaultForRoutingPolylineThin()
    {
        return new VisualParameters(DefaultRoutingLineStrokeThin, DefaultRoutingLineStrokeThin, 4, 1);
    }

    public static VisualParameters GetDefaultForRoutingPolylineThick()
    {
        return new VisualParameters(DefaultRoutingLineThick, DefaultRoutingLineThick, 6, 1);
    }



    public static SolidColorBrush DefaultSelectionStroke = new SolidColorBrush(Colors.Cyan);

    public static SolidColorBrush DefaultSelectionFill = new SolidColorBrush(new Color() { B = 255, G = 255, R = 0, A = 160 });


    public static SolidColorBrush DefaultHighlightStroke = new SolidColorBrush(Colors.Yellow);

    public static SolidColorBrush DefaultHighlightFill = new SolidColorBrush(new Color() { B = 0, G = 255, R = 255, A = 50 });



    public static SolidColorBrush DefaultDrawingStroke = new SolidColorBrush(new Color() { R = 255, G = 200, B = 0, A = 250 });

    public static SolidColorBrush DefaultDrawingFill = new SolidColorBrush(new Color() { R = 255, G = 200, B = 0, A = 160 });


    public static SolidColorBrush DefaultRoutingPointFill = new SolidColorBrush(new Color() { R = 255, G = 228, B = 225, A = 255 });

    public static SolidColorBrush DefaultRoutingPointStroke = new SolidColorBrush(new Color() { R = 220, G = 20, B = 60, A = 255 });


    public static SolidColorBrush DefaultRoutingLineStrokeThin = new SolidColorBrush(new Color() { R = 32, G = 108, B = 213, A = 255 });//#256FD7

    public static SolidColorBrush DefaultRoutingLineThick = new SolidColorBrush(new Color() { R = 102, G = 157, B = 246, A = 255 });//#256FD7


    static readonly Brush _defaultDrawingStroke = BrushHelper.CreateBrush("#FF1CA1E2")!;
    static readonly Brush _defaultDrawingFill = BrushHelper.CreateBrush("#661CA1E2")!;

    private static VisualParameters GetDefaultsForDrawOnMap()
    {
        Brush _fill, _stroke;

        try
        {
            var brush = (SolidColorBrush)Application.Current.Resources["MahApps.Brushes.Accent"];

            if (brush == null)
            {
                _fill = _defaultDrawingFill;

                _stroke = _defaultDrawingStroke;
            }
            else
            {
                _fill = new SolidColorBrush(new Color() { A = 100, R = brush.Color.R, G = brush.Color.G, B = brush.Color.B });

                _stroke = new SolidColorBrush(new Color() { A = 204, R = brush.Color.R, G = brush.Color.G, B = brush.Color.B });
            }
        }
        catch (Exception)
        {
            _fill = _defaultDrawingFill;

            _stroke = _defaultDrawingStroke;
        }

        return new VisualParameters(_fill, _stroke, 2, 0.9);
    }

    public static VisualParameters GetDefaultForMeasurements()
    {
        //return new VisualParameters(BrushHelper.CreateBrush(ColorHelper.ToWpfColor("#FBB03B"), 0.3), BrushHelper.CreateBrush("#FBB03B"), 3, 1)
        //{
        //    DashStyle = new DashStyle([2, 1], 0)
        //};
        var result = GetDefaultsForDrawOnMap();

        result.DashStyle = new DashStyle([2, 1], 0);

        return result;
    }

    public static VisualParameters GetDefaultForDrawing()
    {
        var result = GetDefaultsForDrawOnMap();

        result.DashStyle = new DashStyle([2, 1], 0);

        return result;
    }

    public static VisualParameters GetDefaultForDrawingItems() => new VisualParameters(null, BrushHelper.PickGoodBrush(), 2, 1);

    public static VisualParameters GetDefaultForDrawingItemLabels(Brush foreground)
    {
        return new VisualParameters()
        {
            VisibleRange = ScaleInterval.All,
            FontSize = 13,
            Foreground = foreground,
            FontFamily = new FontFamily("Times New Roman"),
            PositionFunc = i => i.GetCentroidPlusPoint()
        };//
    }

    #endregion


    #region INotifyPropertyChanged

    public event PropertyChangedEventHandler? PropertyChanged;

    protected void RaisePropertyChanged([CallerMemberName] string propertyName = "")
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    #endregion

}
